[package]
name = "ar-core"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = { workspace = true }
polling = { workspace = true }

[dev-dependencies]
once_cell = { workspace = true }
nix = { workspace = true }
